-- Drop existing tables and policies to ensure a clean slate
drop table if exists repairs cascade;
drop table if exists users cascade;

-- Create the users table first (dependency)
create table users (
  phone text primary key,
  name text not null,
  role text default 'CUSTOMER' check (role in ('CUSTOMER', 'ADMIN'))
);

-- Create the repairs table with foreign key
create table repairs (
  id bigint generated by default as identity primary key,
  user_phone text references users(phone),
  "customerName" text not null,
  description text not null,
  status text not null check (status in ('PENDING', 'IN_PROGRESS', 'COMPLETED')),
  date text not null,
  "imageUrl" text,
  analysis jsonb
);

-- Enable Row Level Security (RLS)
alter table repairs enable row level security;
alter table users enable row level security;

-- Create policies that allow all operations for now
create policy "Enable all access for all users on repairs"
on repairs
for all
using (true)
with check (true);

create policy "Enable all access for all users on users"
on users
for all
using (true)
with check (true);
